#Saved token: productionToken
#Wed Sep 02 20:41:55 EEST 2026
CandIencryptedPassword=egFfkhd8cRh82tvsh3VVUg\=\=
DEMO_TOKEN=
SeconDencryptedPassword=egFfkhd8cRh82tvsh3VVUg\=\=
admin_email=hazem.farag@badgewell.com
admin_email_2=hazem.farag+21@badgewell.com
admin_encrypted_password=kpWE379pkw+oGw63Cu+Kmw\=\=
admin_encrypted_password_rc=E8s2VFWtlVzFwcEFLpSCKg\=\=
admin_encrypted_password_rc_2=egFfkhd8cRh82tvsh3VVUg\=\=
admintoken1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhlMWRhM2EzN2E0ZDY2NDEyMWExZTciLCJ1c2VyTmFtZSI6ImhhemVtLmZhcmFnQGJhZGdld2VsbC5jb20iLCJmaXJzdE5hbWUiOiJoYXplbSIsImxhc3ROYW1lIjoibW91cmFkIiwiaXNWZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzg4MzcwOTEzLCJleHAiOjE3ODkyNzA5MTN9.2UXpY8raNDPkqDLgmuDRGnI3Dd5fkFfjeGFUmg2YU7I
admintoken2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImZpcnN0TmFtZSI6IkhhemVtICIsImxhc3ROYW1lIjoiTW91cmFkMiIsImVtYWlsIjoiaGF6ZW0uZmFyYWcrMkBiYWRnZXdlbGwuY29tIiwidHlwZSI6IlRPS0VOIiwiaWF0IjoxNzg4MzcwNDU2LCJleHAiOjE3ODgzOTIwNTZ9.fKfUtewIGRunnuM6CJbpbhy9_IxEJu4XuGEiRZN95Sg
admintokenorg2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgyZmExZTJkMzBmYWYwZjlhYTc1NzIiLCJ1c2VyTmFtZSI6ImhhemVtLmZhcmFnKzIxQGJhZGdld2VsbC5jb20iLCJmaXJzdE5hbWUiOiJIYXplbSIsImxhc3ROYW1lIjoiTW91cmFkIFRXTk9OIiwiaXNWZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzg4MzcwOTE0LCJleHAiOjE3ODkyNzA5MTR9.mqyhiVdmfVLj3QhikNgbEj1X1NNgL3j2-BjA789xsTk
candemail=hazem.farag+77@badgewell.com
candtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTc5YjAzMzk1MzY1MGQ1Njc4NjY2MWIiLCJ1c2VyTmFtZSI6ImhhemVtLmZhcmFnKzc3QGJhZGdld2VsbC5jb20iLCJmaXJzdE5hbWUiOiJIYXplbSIsImxhc3ROYW1lIjoiTW91cmFkIiwiaXNWZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzg4MzcwOTEwLCJleHAiOjE3ODkyNzA5MTB9.JXI2xlprBwYgQHfU8OlerBPl7mCR1qG7PQCY42Au-GU
corporate_admin_email=hazem.farag+125@badgewell.com
corporate_admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTksImZpcnN0TmFtZSI6IkhBWkVNIiwibGFzdE5hbWUiOiJNT1VSQURDQTIiLCJlbWFpbCI6ImhhemVtLmZhcmFnKzEyNUBiYWRnZXdlbGwuY29tIiwidHlwZSI6IlRPS0VOIiwiaWF0IjoxNzg4MzcwNDU3LCJleHAiOjE3ODgzOTIwNTd9.Fu-5jRNI4SRFyjl328OH7p0I0UggKAufB4xpv71MXdY
corporate_encrypted_password=+/7oa9+ivEQELw2KVyGmBA\=\=
demoToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4ODM3MDQ2MCwiZXhwIjoxNzg4Mzc0MDYwfQ.u433fwYJj_AgRMYz7KEls4i3cDZscyFu_PotDdMpbgg
email=hazem.farag@badgewell.com
encryptedPassword=E8s2VFWtlVzFwcEFLpSCKg\=\=
instOne_encrypted_password_rc=egFfkhd8cRh82tvsh3VVUg\=\=
instTwo_encrypted_password_rc=+/7oa9+ivEQELw2KVyGmBA\=\=
instructor_email=hazem.farag+3@badgewell.com
instructor_encrypted_password=keRBR+jh/l+GIZvQK1+GkA\=\=
instructor_one_rc_mail=hazem.farag+114@badgewell.com
instructor_two_rc_mail=hazem.farag+116@badgewell.com
invalidLearnertoken=/|v@l1dT0LEN
invalidToken=1|/|v@l1dT0LEN
invalidadmintoken=@Dm\!n1|/|v@l1dT0LEN
learner_email=hazem.farag+4@badgewell.com
learner_encrypted_password=keRBR+jh/l+GIZvQK1+GkA\=\=
learner_encrypted_password_rc=egFfkhd8cRh82tvsh3VVUg\=\=
learner_one_rc_mail=hazem.farag+117@badgewell.com
learner_two_rc_mail=
learnertoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAxLCJmaXJzdE5hbWUiOiJIYXplbSIsImxhc3ROYW1lIjoiTW91cmFkIE9uZSBPbmUgU2V2ZW4iLCJlbWFpbCI6ImhhemVtLmZhcmFnKzExN0BiYWRnZXdlbGwuY29tIiwidHlwZSI6IlRPS0VOIiwiaWF0IjoxNzg4MzcwNDU4LCJleHAiOjE3ODgzOTIwNTh9.YNSoV_1iizZBsWcVcRLHNrlFR_fI0FVfT7OvshUqb-0
prodEncryptedPassword=E8s2VFWtlVzFwcEFLpSCKg\=\=
productionToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBkZjI3MjE0N2U5ODk0NGRjNmExZDQiLCJ1c2VyTmFtZSI6ImhhemVtLmZhcmFnQGJhZGdld2VsbC5jb20iLCJmaXJzdE5hbWUiOiJoYXplbSIsImxhc3ROYW1lIjoibW91cmFkIiwiaXNWZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzg4MzcwOTE1LCJleHAiOjE3ODkyNzA5MTV9.xcOAUokMRn6IVdKoejUYpMwcxd2XkVAzarlM6pVYjbk
token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTYsImZpcnN0TmFtZSI6IkhhemVtIiwibGFzdE5hbWUiOiJNb3VyYWQgb25lIG9uZSBmb3VyIiwiZW1haWwiOiJoYXplbS5mYXJhZysxMTRAYmFkZ2V3ZWxsLmNvbSIsInR5cGUiOiJUT0tFTiIsImlhdCI6MTc4ODM3MDQ1NiwiZXhwIjoxNzg4MzkyMDU2fQ.w-6HLrA5IRXGV_RE3x1r7jid1UZ_4Y39Z9-r_zNNscY
token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTcsImZpcnN0TmFtZSI6IkhhemVtIE1vdXJhZCIsImxhc3ROYW1lIjoiT25lIE9uZSBTaXgiLCJlbWFpbCI6ImhhemVtLmZhcmFnKzExNkBiYWRnZXdlbGwuY29tIiwidHlwZSI6IlRPS0VOIiwiaWF0IjoxNzg4MzcwNDU3LCJleHAiOjE3ODgzOTIwNTd9.HdRgRBdUiDPJR21thkeXqf7Bky0NJvG32Wco0udI2Ak
url=https\://erp.badgewell.com/auth/login
url_rc=https\://rc.erp.badgewell.com/auth/login
videogame_admin_encrypted_password=GmcYVu1XLNFLwfDvnrzJPw\=\=
videogame_admin_username=admin
